import { Inter } from 'next/font/google'; // Importando a fonte Inter
import './globals.css'; // Certifique-se de ter um arquivo global de estilos
import 'flowbite/dist/flowbite.css';

import { Nav } from "@/components/frontOffice/navbar"; // Seu componente de navegação
import { Footr } from '@/components/frontOffice/footer';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['400', '600'],
});
export const metadata = {
  title: 'Colossos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Nav />
        {children}
        <Footr/>
      </body>
    </html>
  );
}
