import { Inter } from 'next/font/google'; // Importando a fonte Inter
import './globals.css'; // Certifique-se de ter um arquivo global de estilos
import 'flowbite/dist/flowbite.css';

import { Nav } from "@/components/frontOffice/navbar"; // Seu componente de navegação
import { Footr } from '@/components/frontOffice/footer';

const inter = Inter({
  variable: '--font-inter', // Variável CSS para a fonte
  subsets: ['latin'], // Defina os subconjuntos que você precisa (por exemplo, "latin")
  weights: [400, 600], // Você pode adicionar outros pesos, como 400 e 600
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Nav />
        {children}
        <Footr/>
      </body>
    </html>
  );
}
